#!/bin/bash

if [ -f '.env' ]; then
  source .env
fi

if [ -n "$DATABASE_URL" ]; then
  echo "Using... ${DATABASE_URL}"
  sequel -E -r './console.rb' $DATABASE_URL
else
  echo "No DATABASE_URL environment -- cannot connect"
fi
